### ISSUE TITLE
Project Images not loading - returning 404's.

### ISSUE THREAD

**Issue by DiscordAnaxes** [flamexdev/website-template#1]
Hello!

I've noticed that on your personal website, the logo/images for discord-botlist.eu & dsleu.org no longer exist from the paths provided. 

<img src="https://us.tixte.net/uploads/cdn.anaxes.xyz/ks4jd69vg9a.png"/>

**Comment by flamexdev** [comment]
Ah yea, thank you!
I forgot to update them. I will in the course of the next one or two days take a few minutes to fix it
